version: '3'

services:

    ic-sql-server:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: ic-sql-server
        hostname: ic-sql-server
        restart: always
        working_dir: /app
        environment:
            ACCEPT_EULA: 'Y'
            MSSQL_SA_PASSWORD: $IC_SQL_PSWD
            MSSQL_PID: $IC_SQL_PID
        ports:
        - $IC_SQL_PORT:$IC_SQL_PORT
        volumes:
        - ic-sql-server-data:/data
        - ./database:/confs:delegated
        networks:
        - ic-network

    ic-app:
        container_name: ic-app
        hostname: ic-app
        build:
            context: .
        working_dir: /app
        command: dotnet watch run urls=http://$IC_APP_HOST:$IC_APP_PORT
        tty: true
        env_file: .env
        ports:
        - $IC_APP_PORT:$IC_APP_PORT
        volumes:
        - .:/app:delegated
        - home:/home/$LOCAL_USER_NAME
        networks:
        - ic-network

volumes:
    ic-sql-server-data:
    home:

networks:
    ic-network:
